swagger: '2.0'
info:
  version: 1.0.0
  title: PME-Receivables-Anticipation-BR
  description: >-
    This API persist and returns the receivables information.
  contact:
    name: Squad Gestão Financeira
    email: squadgestaofinanceira@br.experian.com
host: sandbox-api.serasaexperian.com.br
basePath: /serasaempreendedor/receivables-anticipation/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  OauthSecurityUser:
    type: oauth2
    flow: password
    tokenUrl: https://sandbox-api.serasaexperian.com.br/security/iam/v1/user-identities/login
    scopes:
      read: User read scope

paths:
  /onboarding:
    get:
      tags:
        - Onboarding
      description: Retrive onboarding status
      summary: Retrive onboarding status
      security:
        - OauthSecurityUser:
            - read
      operationId: retrieveStatus
      responses:
        200:
          description: The request was successful
          schema:
            $ref: "#/definitions/OnboardingResponse"
        204:
          description: Not started
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorModel'
        424:
          description: Failed Dependency
          schema:
            $ref: '#/definitions/ErrorModel'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorModel'
        default:
          description: Unexpected Error
    post:
      tags:
        - Onboarding
      description: Start onboarding process
      summary: Start onboarding process
      security:
        - OauthSecurityUser:
            - read
      operationId: accept
      responses:
        204:
          description: The request was successful
          headers:
            location:
              type: string
              description: 'Redirect URL: https://cadastro.pagbank.com.br/serasa-empreendedor'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorModel'
        424:
          description: Failed Dependency
          schema:
            $ref: '#/definitions/ErrorModel'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorModel'
        default:
          description: Unexpected Error
  /history:
    get:
      tags:
        - History
      description: Retrieve anticipation history
      summary: Retrieve anticipation history
      security:
        - OauthSecurityUser:
            - read
      operationId: findHistory
      parameters:
        - name: capitalSourceDocument
          in: query
          description: Capital source document to filter anticipation
          required: false
          type: string
        - name: anticipationDate
          in: query
          description: Anticipation date to filter (format YYYY-MM-DD)
          required: false
          type: string
          format: date
        - name: statusId
          in: query
          description: Status ID to filter anticipations
          required: false
          type: string
        - name: pageId
          in: query
          description: Page ID for pagination
          required: false
          type: string
        - name: pageSize
          in: query
          description: Number of items per page
          required: false
          type: integer
          minimum: 1
          maximum: 100
          default: 10
      responses:
        200:
          description: The Request was successful
          schema:
            $ref: "#/definition/AnticipationHistoryResponse"
        204:
          description: No Content
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorModel'
        424:
          description: Failed Dependency
          schema:
            $ref: '#/definitions/ErrorModel'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorModel'
        default:
          description: Unexpected Error
  /history/{id}:
    get:
      tags:
        - History
      description: Retrieve specific anticipation details
      summary: Retrieve anticipation details by ID
      security:
        - OauthSecurityUser:
            - read
      operationId: findHistoryById
      parameters:
        - name: id
          in: path
          description: Anticipation ID
          required: true
          type: string
      responses:
        200:
          description: The Request was successful
          schema:
            $ref: "#/definition/AnticipationDetailResponse"
        404:
          description: Not found
          schema:
            $ref: '#/definitions/ErrorModel'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorModel'
        424:
          description: Failed Dependency
          schema:
            $ref: '#/definitions/ErrorModel'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorModel'
        default:
          description: Unexpected Error

  /receivables:
    get:
      tags:
        - Receivables
      description: Retrieve available receivables grouped by payment date
      summary: Retrieve available receivables
      security:
        - OauthSecurityUser:
            - read
      operationId: findAvailables
      parameters:
        - name: date
          in: query
          description: Payment date to filter receivables (format YYYY-MM-DD). Defaults to today's date if not provided.
          required: false
          type: string
          format: date
        - name: limit
          in: query
          description: Maximum number of receivables to return
          required: false
          type: integer
          minimum: 1
          maximum: 100
          default: 10
        - name: offset
          in: query
          description: Number of receivables to skip for pagination
          required: false
          type: integer
          minimum: 0
          default: 0
      responses:
        200:
          description: The request was successful
          schema:
            $ref: "#/definitions/ReceivableGroupedResponse"
        400:
          description: Bad Request
          schema:
            $ref: "#/definitions/ErrorModel"
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorModel'
        424:
          description: Failed Dependency
          schema:
            $ref: '#/definitions/ErrorModel'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorModel'
        default:
          description: Unexpected Error

definitions:
  OnboardingResponse:
    type: object
    properties:
      status:
        $ref: '#/definitions/OnboardingStatus'
  OnboardingStatus:
    type: string
    enum:
      - STARTED
      - REVIEW
      - PENDING
      - APPROVED
      - REJECTED

  AnticipationHistoryResponse:
    type: object
    properties:
      items:
        type: array
        items:
        $ref: '#/definitions/AnticipationHistoryItem'
      pageNexId:
        type: string
      pageSize:
        type: integer

  AnticipationHistoryItem:
    type: object
    properties:
      id:
        type: string
        example: 'f63985b1-619d-4514-ab19-bd19-bd1ec6f69ab0'
      number:
        type: integer
        example: 12345
      receivablesCount:
        type: integer
        example: 5
        description: Number of receivables included in the anticipation
      accreditingInstitution:
        $ref: '#/definitions/AccreditingInstitution'
      capitalSource:
        $ref: '#/definitions/CapitalSource'
      supplier:
        $ref: '#/definitions/Supplier'
      requestedBy:
        type: string
        example: 'user@example.com'
      status:
        type: string
        enum: ['PENDING', 'CONCLUDED', 'PARTIALLY_APPROVED', 'ERROR']
        example: 'APPROVED'
        description: 'Mapped status with API: PENDING (Created/Processing), CONCLUDED (Anticipated),
         PARTIALLY_APPROVED (PartiallyAnticipated), ERROR (AnticipationFailed)'
      statusId:
        type: integer
        example: 1
        description: 'ID status: 1=PENDING, 2=CONCLUDED, 3=PARTIALLY_APPROVED, 4=ERROR'
      createdAt:
        type: string
        format: data-time
        example: '2025-01-15T10:30:00Z'
      paymentDate:
        type: string
        format: date-time
        example: '2025-01-15T10:30:00Z'
      amount:
        type: number
        example: 15000.50
      requestRate:
        type: number
        example: 2.5
      effectiveRate:
        type: number
        example: 2.3
      selectedAmount:
        type: number
        example: 14500.00
      receivedAmount:
        type: number
        example: 14165.50

  AnticipationDetailResponse:
    type: object
    properties:
      id:
        type: string
        example: 'f63985b1-619d-4514-ab19-bd19-bd1ec6f69ab0'
      receivablesCount:
        type: integer
        example: 5
        description: Number of receivables included in the anticipation
      accreditingInstitution:
        $ref: '#/definitions/AccreditingInstitution'
      capitalSource:
        $ref: '#/definitions/CapitalSource'
      supplier:
        $ref: '#/definitions/Supplier'
      number:
        type: integer
        example: 12345
      requestedBy:
        type: string
        example: 'user@example.com'
      status:
        type: string
        enum: ['PENDING', 'CONCLUDED', 'PARTIALLY_APPROVED', 'ERROR']
        example: 'PENDING'
      statusId:
        type: integer
        example: 1
      mediumTerm:
        type: number
        example: 15.5
      paymentDate:
        type: string
        format: date-time
        example: '2025-01-15T10:30:00Z'
      createdAt:
        type: string
        format: date-time
        example: '2025-01-15T10:30:00Z'
      amount:
        type: number
        example: 15000.50
      requestedRate:
        type: number
        example: 2.5
      effectiveRate:
        type: number
        example: 2.5
      selectedAmount:
        type: number
        example: 14500.00
      receivedAmount:
        type: number
        example: 14165.50
      bankAccount:
        $ref: '#/definitions/BankAccount'
      anticipatedItems:
        type: array
        items:
          $ref: '#/definitions/AnticipatedItem'
      noAnticipatedItems:
        type: array
        items:
          $ref: '#/definitions/AnticipatedItem'

  AccreditingInstitution:
    type: object
    properties:
      document:
        type: string
        example: '12345678000190'
      name:
        type: string
        example: 'Cielo S.A'

  CapitalSource:
    type: object
    properties:
      document:
        type: string
        example: '98765432000110'
      name:
        type: string
        example: 'Antecipa Pagamentos'

  Supplier:
    type: object
    properties:
      document:
        type: string
        example: '11222333000144'
      name:
        type: string
        example: 'Supplier Company Ltda'

  bankAccount:
    type: object
    properties:
      bank:
        type: string
        example: '001'
      agency:
        type: string
        example: '1234'
      account:
        type: string
        example: '567890'
      accountType:
        type: string
        example: 'CHECKING'

  AnticipatedItem:
    type: object
    properties:
      id:
        type: string
        example: 'item-123'
      externalId:
        type: string
        example: 'ext-456'
      status:
        type: string
        example: 'ANTICIPATED'
      amount:
        type: number
        example: 1500.75
      anticipationResponseMessage:
        type: string
        example: 'Successfully anticipated'

  ReceivableGroupedResponse:
    type: object
    properties:
      content:
        type: array
        items:
          $ref: '#/definitions/ReceivableGroup'
      page:
        $ref: '#/definitions/Pagination'

  ReceivableGroup:
    type: object
    properties:
      paymentDate:
        type: string
        example: '2025-07-22'
      count:
        type: integer
        example: 5
      totalAmountToReceive:
        type: number
        example: '7422.25'
      items:
        type: array
        items:
          $ref: '#/definitions/ReceivableData'
  ReceivableData:
    type: object
    properties:
      id:
        type: string
        example: 'f63985b1-619d-4514-ab19-bd1ec6f69ab0'
      paymentDate:
        type: string
        example: '2025-07-22'
      nationalRegistrationId:
        type: string
        example: '18772021000190'
      accreditingInstitutionName:
        type: string
        example: 'Cielo'
      paymentType:
        $ref: '#/definitions/PaymentType'
      installment:
        $ref: '#/definitions/InstallmentData'
      discount:
        type: number
        example: '50.00'
      amountToReceive:
        type: number
        example: '1484.45'
  PaymentType:
    type: string
    enum:
      - CREDIT_SINGLE
      - CREDIT_INSTALLMENT
    example: 'CREDIT_INSTALLMENT'
  InstallmentData:
    type: object
    properties:
      count:
        type: integer
        example: '3'
      number:
        type: integer
        example: '1'
      amount:
        type: number
        example: '1534.45'
      paymentType:
        $ref: '#/definitions/PaymentType'
      discount:
        type: number
        example: '50.00'
  Pagination:
    type: object
    properties:
      size:
        type: integer
        example: 10
      totalElements:
        type: integer
        example: 50
      totalPages:
        type: integer
        example: 5
      number:
        type: integer
        example: 1

  ErrorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: string
      message:
        type: string
